# Generated by Django 5.0.7 on 2024-08-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0002_alter_unidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='nombre',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
