# Generated by Django 5.0.7 on 2024-08-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0006_prestamodevuelto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamodevuelto',
            name='fecha_entregado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prestamodevuelto',
            name='fecha_recibido',
            field=models.DateField(auto_now_add=True),
        ),
    ]
