# Generated by Django 5.0.7 on 2024-08-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0007_alter_prestamodevuelto_fecha_entregado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamodevuelto',
            options={'verbose_name_plural': 'prestamos devueltos'},
        ),
    ]
