# Generated by Django 5.0.7 on 2024-09-04 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0010_inventario_bloque_alter_inventario_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('tipo', models.IntegerField(choices=[(1, 'Permanente'), (0, 'Temporal'), (-1, 'Retornado')], default=1)),
                ('fecha_transferido', models.DateField(auto_now_add=True)),
                ('fecha_retornado', models.DateField(null=True)),
                ('bloque_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_destino_set', to='Almacen.bloque')),
                ('bloque_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_origen_set', to='Almacen.bloque')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.producto')),
                ('retornado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retornado_usuario_set', to=settings.AUTH_USER_MODEL)),
                ('transferido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferido_usuario_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
