# Generated by Django 5.0.7 on 2025-02-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0013_producto_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nss',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tel',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
