# Generated by Django 5.0.7 on 2025-02-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0014_empleado_direccion_empleado_foto_empleado_nss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
