# Generated by Django 5.1.6 on 2025-02-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0016_empleado_tel_emg'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='gafete_pdf',
            field=models.FileField(blank=True, null=True, upload_to='gafetes/'),
        ),
    ]
