# Generated by Django 5.1.6 on 2025-02-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0018_alter_empleado_nss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='nss',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tel_emg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
