# Generated by Django 5.0.7 on 2025-11-12 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0023_requisicion_especialidad_alter_requisicion_bloque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='ID único del usuario en Telegram', unique=True, verbose_name='ID de Telegram')),
                ('username', models.CharField(blank=True, help_text='Nombre de usuario en Telegram (@username)', max_length=255, null=True, verbose_name='Username de Telegram')),
                ('first_name', models.CharField(blank=True, help_text='Nombre del usuario en Telegram', max_length=255, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, help_text='Apellido del usuario en Telegram', max_length=255, null=True, verbose_name='Apellido')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se registró el usuario', verbose_name='Fecha de registro')),
                ('fecha_ultimo_acceso', models.DateTimeField(auto_now=True, help_text='Fecha del último acceso al bot', verbose_name='Último acceso')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario está activo en el bot', verbose_name='Activo')),
                ('empleado', models.ForeignKey(blank=True, help_text='Empleado asociado a este usuario de Telegram', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Almacen.empleado', verbose_name='Empleado')),
                ('usuario_django', models.ForeignKey(blank=True, help_text='Usuario de Django asociado', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django')),
            ],
            options={
                'verbose_name': 'Usuario de Telegram',
                'verbose_name_plural': 'Usuarios de Telegram',
                'ordering': ['-fecha_ultimo_acceso'],
            },
        ),
    ]
