# Generated by Django 5.1.6 on 2025-11-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0026_requisicion_solicitante_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen adjunta a la requisición', null=True, upload_to='requisiciones/'),
        ),
    ]
