# Generated by Django 5.1.6 on 2025-11-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0027_requisicion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='imagen',
            field=models.ImageField(default='requisiciones/default.jpg', help_text='Imagen obligatoria adjunta a la requisición', upload_to='requisiciones/'),
        ),
    ]
