# Generated by Django 5.1.6 on 2025-11-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0028_alter_requisicion_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('temporal', 'Temporal'), ('empleado', 'Empleado'), ('supervisor', 'Supervisor'), ('directivo', 'Directivo')], default='empleado', help_text='Rol o nivel del empleado en la organización', max_length=20),
        ),
    ]
