# Generated by Django 5.1.6 on 2025-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0031_requisicion_supervisor_alter_requisicion_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='es_herramienta',
        ),
        migrations.AddField(
            model_name='producto',
            name='especialidad',
            field=models.CharField(default='consumible', max_length=50),
        ),
    ]
