# Generated by Django 5.1.6 on 2025-12-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0032_remove_producto_es_herramienta_producto_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('temporal', 'Temporal'), ('general', 'General'), ('chofer', 'Chofer'), ('bodeguero', 'Bodeguero'), ('supervisor', 'Supervisor'), ('directivo', 'Directivo')], default='general', help_text='Rol o nivel del empleado en la organización', max_length=20),
        ),
    ]
