# Generated by Django 5.1.6 on 2025-12-15 19:53

import Almacen.models.requisiciones.requisiciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0036_alter_producto_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='detalles_productos',
            field=models.JSONField(default=list, help_text='Lista de hasta 14 productos con sus detalles', validators=[Almacen.models.requisiciones.requisiciones.Requisicion.validar_max_productos]),
        ),
    ]
