# Generated by Django 6.0 on 2025-12-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0037_requisicion_detalles_productos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicion',
            options={'verbose_name': 'Requisición', 'verbose_name_plural': 'Requisiciones'},
        ),
    ]
