# Generated by Django 5.0.7 on 2024-08-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name_plural': 'unidades'},
        ),
    ]
