# Generated by Django 5.0.7 on 2024-08-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0003_alter_bloque_nombre_alter_empleado_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Entrada'), (0, 'Salida'), (-1, 'Prestado')], default=1),
        ),
    ]
