# Generated by Django 5.0.7 on 2024-08-26 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0005_registro_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoDevuelto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('fecha_entregado', models.DateField(auto_now_add=True)),
                ('fecha_recibido', models.DateField(auto_now=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.bloque')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.empleado')),
                ('entregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_entregados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.producto')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
