# Generated by Django 5.0.7 on 2024-08-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0008_alter_prestamodevuelto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'permissions': [('can_use_register_form', 'Can use the product in/out register form')]},
        ),
    ]
