# Generated by Django 5.0.7 on 2024-09-03 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0009_alter_registro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='bloque',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='Almacen.bloque'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('bloque', 'producto')},
        ),
    ]
