# Generated by Django 5.0.7 on 2024-09-04 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0011_transferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='fecha_retornado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='retornado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retornado_usuario_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
