# Generated by Django 5.0.7 on 2024-09-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0012_alter_transferencia_fecha_retornado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alerta',
            field=models.FloatField(default=0.0),
        ),
    ]
