# Generated by Django 5.1.6 on 2025-02-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0015_alter_empleado_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tel_emg',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
