# Generated by Django 5.1.6 on 2025-02-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0017_empleado_gafete_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='nss',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
