# Generated by Django 5.1.6 on 2025-02-19 10:56

import Almacen.models.personal.personal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0019_alter_empleado_nss_alter_empleado_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=Almacen.models.personal.personal.renombrar_foto_empleado),
        ),
    ]
