# Generated by Django 5.1.6 on 2025-11-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0020_alter_empleado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
