# Generated by Django 5.1.6 on 2025-11-09 20:18

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0021_transferencia_observaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='herramienta',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.CharField(default='REQTEMP', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('obra', models.CharField(default='Obra sin especificar', max_length=200)),
                ('ubicacion', models.CharField(default='Ubicación no definida', max_length=200)),
                ('fecha_soli', models.DateField(default=datetime.date.today)),
                ('fecha_util', models.DateField(blank=True, default=None, null=True)),
                ('fecha_surt', models.DateField(blank=True, default=None, null=True)),
                ('autorizado_supervisor', models.BooleanField(default=False)),
                ('autorizado_directivo', models.BooleanField(default=False)),
                ('estado', models.CharField(default='pendiente', help_text='Estados posibles: pendiente / autorizada / rechazada / surtida', max_length=20)),
                ('observaciones', models.TextField(blank=True, default=None, null=True)),
                ('numero_de_articulos', models.IntegerField(default=0)),
                ('bloque', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.bloque')),
                ('solicitante', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.empleado')),
                ('usuario_creador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
