# Generated by Django 5.1.6 on 2025-11-12 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0022_producto_herramienta_requisicion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='especialidad',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='bloque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.bloque'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='estado',
            field=models.CharField(default='pendiente', help_text='Estados: pendiente / supervisor / autorizada / rechazada / surtida / cerrada', max_length=30),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='fecha_surt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='fecha_util',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.empleado'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetalleRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.producto')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Almacen.requisicion')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Almacen.unidad')),
            ],
        ),
    ]
