# Generated by Django 5.0.7 on 2025-11-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0024_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_herramienta',
            field=models.BooleanField(default=False),
        ),
    ]
