# Generated by Django 5.0.7 on 2025-11-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0025_producto_es_herramienta'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='solicitante_nombre',
            field=models.CharField(blank=True, help_text='Nombre del solicitante cuando no está vinculado a un empleado', max_length=200, null=True),
        ),
    ]
