# Generated by Django 5.1.6 on 2025-11-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0029_alter_empleado_options_empleado_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='ID de Telegram del usuario para notificaciones', max_length=50, null=True),
        ),
    ]
