# Generated by Django 5.1.6 on 2025-11-24 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0030_empleado_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor asignado para revisar esta requisición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_supervisadas', to='Almacen.empleado'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_solicitadas', to='Almacen.empleado'),
        ),
    ]
