# Generated by Django 5.1.6 on 2025-12-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0033_alter_empleado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='especialidad',
            field=models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('obra_civil', 'Obra Civil'), ('pintura_tablaroca', 'Pintura y Tablaroca'), ('vidrio_canceleria', 'Vidrio y Canceleria'), ('herreria', 'Herrería'), ('herramienta', 'Herramienta')], default='consumible', help_text='Seleccione la especialidad del producto. Si es una herramienta, se establecerá automáticamente.', max_length=50),
        ),
    ]
